Auth
syshim77/Chinstagram-Back pull request #3
Opened 2020-07-28 19:06 UTC by syshim77

- Add caching in JwtService
- Cache LogInRequest user information

2020-07-29 01:15 UTC, KeonHee requested changes

2020-07-29 01:15 UTC, KeonHee commented on Chinstagram/src/main/java/com/landvibe/chinstagram/ChinstagramApplication.java
> +        //SpringApplication.run(ChinstagramApplication.class, args);
필요 없는 주석은 삭제

2020-07-29 01:15 UTC, KeonHee commented on Chinstagram/src/main/java/com/landvibe/chinstagram/jwt/JwtService.java
> +    private final String SECRET_KEY;
aws의 credential을 jwt의 secret으로 설정한 이유는 머야?

2020-07-29 01:15 UTC, KeonHee commented on Chinstagram/src/main/java/com/landvibe/chinstagram/jwt/JwtService.java
> +            key = SECRET_KEY.getBytes("UTF-8");
굳이 런타임에 btye[]로 변환하는 이유는??

2020-07-29 01:15 UTC, KeonHee commented on Chinstagram/src/main/java/com/landvibe/chinstagram/jwt/JwtService.java
> +                    .setSigningKey(SECRET_KEY.getBytes("UTF-8"))
근데 또 여기서는 generateKey을 안썼네

2020-07-29 01:15 UTC, KeonHee commented on Chinstagram/src/main/java/com/landvibe/chinstagram/services/ContentService.java
> +    private S3Uploader s3Uploader;
s3 pr이 따로 올라왔는데 왜 여기추가되어 있는거야?

2020-07-29 06:24 UTC, syshim77 commented on Chinstagram/src/main/java/com/landvibe/chinstagram/jwt/JwtService.java
> +    private final String SECRET_KEY;
이거 s3에다가 바꿔서 올렸어요ㅠ

2020-07-29 06:25 UTC, syshim77 commented on Chinstagram/src/main/java/com/landvibe/chinstagram/services/ContentService.java
> +    private S3Uploader s3Uploader;
s3 작업을 하고나서 이거를 수정해서 올린거여서 s3 부분 삭제한다고 한건데 못지운 부분이에요ㅠ

2020-07-29 06:27 UTC, syshim77 commented on Chinstagram/src/main/java/com/landvibe/chinstagram/jwt/JwtService.java
> +                    .setSigningKey(SECRET_KEY.getBytes("UTF-8"))
이 부분은 키 생성이 아니라 생성된 키에서 유저 정보 가져오는 부분이라서 generateKey 부분이 없어요

2020-07-29 06:27 UTC, syshim77 commented on Chinstagram/src/main/java/com/landvibe/chinstagram/jwt/JwtService.java
> +            key = SECRET_KEY.getBytes("UTF-8");
byte로 하는건 제가 본 예제 코드에 그렇게 되어있어서 한거였는데.. 이유는 좀 더 알아볼게요ㅠ

2020-07-30 00:07 UTC, KeonHee commented on Chinstagram/src/main/java/com/landvibe/chinstagram/jwt/JwtService.java
> +                    .setSigningKey(SECRET_KEY.getBytes("UTF-8"))
```java
 private byte[] generateKey() throws Exception {
        byte[] key = null;

        try {
            key = SECRET_KEY.getBytes("UTF-8");
         } catch(UnsupportedEncodingException e) {
            throw new UnsupportedEncodingException("Unsupported Encoding Exception while generating key.");
        }
        return key;
    }
```

`generateKey()`랑 `SECRET_KEY.getBytes("UTF-8"))` 이거 결국 `SECRET_KEY` 값을 byte[]로 변환하는건데, 기껏 함수로 만들어놓고 안쓰는게 이해가 안되서~ `getSecretKey()` 정도로 이름 바꾼 다음에 돌려쓰는게 좋지않을까?

2020-07-30 00:10 UTC, KeonHee commented on Chinstagram/src/main/java/com/landvibe/chinstagram/jwt/JwtService.java
> +            key = SECRET_KEY.getBytes("UTF-8");
byte[]로 변경한건 `signWith`의 파라미터가 byte[]니까 어쩔수 없는 건데, 내 질문의 요점은 왜 '런타임'에 변환을 해서 try ~ catch까지 잡았는지야. 보면 설정값 을 불러다가 byte[]로 변환하는건데, 이건 런타임이 아니라 스프링이 실행되는 부트타임에 잡아야 하는거아니야?

2020-07-30 00:11 UTC, KeonHee commented on Chinstagram/src/main/java/com/landvibe/chinstagram/services/ContentService.java
> +    private S3Uploader s3Uploader;
번거롭겠지만 이 PR에서는 S3관련 내용들은 삭제하는게 좋을듯

2020-07-30 11:18 UTC, syshim77 commented on Chinstagram/src/main/java/com/landvibe/chinstagram/jwt/JwtService.java
> +            key = SECRET_KEY.getBytes("UTF-8");
아.. 제가 잘못 이해했어요..ㅎ 좀 찾아봤는데 한번 말씀해주신대로 바꿔서 다시 PR 날려볼게요!

2020-07-30 11:22 UTC, syshim77 commented on Chinstagram/src/main/java/com/landvibe/chinstagram/jwt/JwtService.java
> +                    .setSigningKey(SECRET_KEY.getBytes("UTF-8"))
아아 네넵! 알겠습니다ㅎ

2020-07-30 11:23 UTC, syshim77 commented on Chinstagram/src/main/java/com/landvibe/chinstagram/services/ContentService.java
> +    private S3Uploader s3Uploader;
네넵!

2020-07-30 11:50 UTC, closed without merging